Fix Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
== Cause Error ==
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
http://stackoverflow.com/questions/14376879/error-10-digest-iterations-reached-aborting-with-dynamic-sortby-predicate

== Info ==
angular#1.3.11
bootstrap#3.0.3
bootstrap-daterangepicker#1.3.19